-- Populate a list of countries used for the country select dropdown in the React application

\connect game_library

BEGIN;

INSERT INTO country(name) values('Afghanistan');
INSERT INTO country(name) values('Albania');
INSERT INTO country(name) values('Algeria');
INSERT INTO country(name) values('Andorra');
INSERT INTO country(name) values('Angola');
INSERT INTO country(name) values('Anguilla');
INSERT INTO country(name) values('Antigua & Barbuda');
INSERT INTO country(name) values('Argentina');
INSERT INTO country(name) values('Armenia');
INSERT INTO country(name) values('Australia');
INSERT INTO country(name) values('Austria');
INSERT INTO country(name) values('Azerbaijan');
INSERT INTO country(name) values('Bahamas');
INSERT INTO country(name) values('Bahrain');
INSERT INTO country(name) values('Bangladesh');
INSERT INTO country(name) values('Barbados');
INSERT INTO country(name) values('Belarus');
INSERT INTO country(name) values('Belgium');
INSERT INTO country(name) values('Belize');
INSERT INTO country(name) values('Benin');
INSERT INTO country(name) values('Bermuda');
INSERT INTO country(name) values('Bhutan');
INSERT INTO country(name) values('Bolivia');
INSERT INTO country(name) values('Bosnia & Herzegovina');
INSERT INTO country(name) values('Botswana');
INSERT INTO country(name) values('Brazil');
INSERT INTO country(name) values('Brunei Darussalam');
INSERT INTO country(name) values('Bulgaria');
INSERT INTO country(name) values('Burkina Faso');
INSERT INTO country(name) values('Burundi');
INSERT INTO country(name) values('Cambodia');
INSERT INTO country(name) values('Cameroon');
INSERT INTO country(name) values('Canada');
INSERT INTO country(name) values('Cape Verde');
INSERT INTO country(name) values('Cayman Islands');
INSERT INTO country(name) values('Central African Republic');
INSERT INTO country(name) values('Chad');
INSERT INTO country(name) values('Chile');
INSERT INTO country(name) values('China');
INSERT INTO country(name) values('China - Hong Kong / Macau');
INSERT INTO country(name) values('Colombia');
INSERT INTO country(name) values('Comoros');
INSERT INTO country(name) values('Congo');
INSERT INTO country(name) values('Congo, Democratic Republic of (DRC)');
INSERT INTO country(name) values('Costa Rica');
INSERT INTO country(name) values('Croatia');
INSERT INTO country(name) values('Cuba');
INSERT INTO country(name) values('Cyprus');
INSERT INTO country(name) values('Czech Republic');
INSERT INTO country(name) values('Denmark');
INSERT INTO country(name) values('Djibouti');
INSERT INTO country(name) values('Dominica');
INSERT INTO country(name) values('Dominican Republic');
INSERT INTO country(name) values('Ecuador');
INSERT INTO country(name) values('Egypt');
INSERT INTO country(name) values('El Salvador');
INSERT INTO country(name) values('Equatorial Guinea');
INSERT INTO country(name) values('Eritrea');
INSERT INTO country(name) values('Estonia');
INSERT INTO country(name) values('Eswatini');
INSERT INTO country(name) values('Ethiopia');
INSERT INTO country(name) values('Fiji');
INSERT INTO country(name) values('Finland');
INSERT INTO country(name) values('France');
INSERT INTO country(name) values('French Guiana');
INSERT INTO country(name) values('Gabon');
INSERT INTO country(name) values('Gambia, Republic of The');
INSERT INTO country(name) values('Georgia');
INSERT INTO country(name) values('Germany');
INSERT INTO country(name) values('Ghana');
INSERT INTO country(name) values('Great Britain');
INSERT INTO country(name) values('Greece');
INSERT INTO country(name) values('Grenada');
INSERT INTO country(name) values('Guadeloupe');
INSERT INTO country(name) values('Guatemala');
INSERT INTO country(name) values('Guinea');
INSERT INTO country(name) values('Guinea-Bissau');
INSERT INTO country(name) values('Guyana');
INSERT INTO country(name) values('Haiti');
INSERT INTO country(name) values('Honduras');
INSERT INTO country(name) values('Hungary');
INSERT INTO country(name) values('Iceland');
INSERT INTO country(name) values('India');
INSERT INTO country(name) values('Indonesia');
INSERT INTO country(name) values('Iran');
INSERT INTO country(name) values('Iraq');
INSERT INTO country(name) values('Israel and the Occupied Territories');
INSERT INTO country(name) values('Italy');
INSERT INTO country(name) values('Ivory Coast');
INSERT INTO country(name) values('Jamaica');
INSERT INTO country(name) values('Japan');
INSERT INTO country(name) values('Jordan');
INSERT INTO country(name) values('Kazakhstan');
INSERT INTO country(name) values('Kenya');
INSERT INTO country(name) values('Korea, Democratic Republic of (North Korea)');
INSERT INTO country(name) values('Korea, Republic of (South Korea)');
INSERT INTO country(name) values('Kosovo');
INSERT INTO country(name) values('Kuwait');
INSERT INTO country(name) values('Kyrgyz Republic (Kyrgyzstan)');
INSERT INTO country(name) values('Laos');
INSERT INTO country(name) values('Latvia');
INSERT INTO country(name) values('Lebanon');
INSERT INTO country(name) values('Lesotho');
INSERT INTO country(name) values('Liberia');
INSERT INTO country(name) values('Libya');
INSERT INTO country(name) values('Liechtenstein');
INSERT INTO country(name) values('Lithuania');
INSERT INTO country(name) values('Luxembourg');
INSERT INTO country(name) values('Madagascar');
INSERT INTO country(name) values('Malawi');
INSERT INTO country(name) values('Malaysia');
INSERT INTO country(name) values('Maldives');
INSERT INTO country(name) values('Mali');
INSERT INTO country(name) values('Malta');
INSERT INTO country(name) values('Martinique');
INSERT INTO country(name) values('Mauritania');
INSERT INTO country(name) values('Mauritius');
INSERT INTO country(name) values('Mayotte');
INSERT INTO country(name) values('Mexico');
INSERT INTO country(name) values('Moldova, Republic of');
INSERT INTO country(name) values('Monaco');
INSERT INTO country(name) values('Mongolia');
INSERT INTO country(name) values('Montenegro');
INSERT INTO country(name) values('Montserrat');
INSERT INTO country(name) values('Morocco');
INSERT INTO country(name) values('Mozambique');
INSERT INTO country(name) values('Myanmar/Burma');
INSERT INTO country(name) values('Namibia');
INSERT INTO country(name) values('Nepal');
INSERT INTO country(name) values('New Zealand');
INSERT INTO country(name) values('Nicaragua');
INSERT INTO country(name) values('Niger');
INSERT INTO country(name) values('Nigeria');
INSERT INTO country(name) values('North Macedonia, Republic of');
INSERT INTO country(name) values('Norway');
INSERT INTO country(name) values('Oman');
INSERT INTO country(name) values('Pacific Islands');
INSERT INTO country(name) values('Pakistan');
INSERT INTO country(name) values('Panama');
INSERT INTO country(name) values('Papua New Guinea');
INSERT INTO country(name) values('Paraguay');
INSERT INTO country(name) values('Peru');
INSERT INTO country(name) values('Philippines');
INSERT INTO country(name) values('Poland');
INSERT INTO country(name) values('Portugal');
INSERT INTO country(name) values('Puerto Rico');
INSERT INTO country(name) values('Qatar');
INSERT INTO country(name) values('Reunion');
INSERT INTO country(name) values('Romania');
INSERT INTO country(name) values('Russian Federation');
INSERT INTO country(name) values('Rwanda');
INSERT INTO country(name) values('Saint Kitts and Nevis');
INSERT INTO country(name) values('Saint Lucia');
INSERT INTO country(name) values('Saint Vincent and the Grenadines');
INSERT INTO country(name) values('Samoa');
INSERT INTO country(name) values('Sao Tome and Principe');
INSERT INTO country(name) values('Saudi Arabia');
INSERT INTO country(name) values('Senegal');
INSERT INTO country(name) values('Serbia');
INSERT INTO country(name) values('Seychelles');
INSERT INTO country(name) values('Sierra Leone');
INSERT INTO country(name) values('Singapore');
INSERT INTO country(name) values('Slovak Republic (Slovakia)');
INSERT INTO country(name) values('Slovenia');
INSERT INTO country(name) values('Solomon Islands');
INSERT INTO country(name) values('Somalia');
INSERT INTO country(name) values('South Africa');
INSERT INTO country(name) values('South Sudan');
INSERT INTO country(name) values('Spain');
INSERT INTO country(name) values('Sri Lanka');
INSERT INTO country(name) values('Sudan');
INSERT INTO country(name) values('Suriname');
INSERT INTO country(name) values('Sweden');
INSERT INTO country(name) values('Switzerland');
INSERT INTO country(name) values('Syria');
INSERT INTO country(name) values('Tajikistan');
INSERT INTO country(name) values('Tanzania');
INSERT INTO country(name) values('Thailand');
INSERT INTO country(name) values('Netherlands');
INSERT INTO country(name) values('Timor Leste');
INSERT INTO country(name) values('Togo');
INSERT INTO country(name) values('Trinidad & Tobago');
INSERT INTO country(name) values('Tunisia');
INSERT INTO country(name) values('Turkey');
INSERT INTO country(name) values('Turkmenistan');
INSERT INTO country(name) values('Turks & Caicos Islands');
INSERT INTO country(name) values('Uganda');
INSERT INTO country(name) values('Ukraine');
INSERT INTO country(name) values('United Arab Emirates');
INSERT INTO country(name) values('United States of America (USA)');
INSERT INTO country(name) values('Uruguay');
INSERT INTO country(name) values('Uzbekistan');
INSERT INTO country(name) values('Venezuela');
INSERT INTO country(name) values('Vietnam');
INSERT INTO country(name) values('Virgin Islands (UK)');
INSERT INTO country(name) values('Virgin Islands (US)');
INSERT INTO country(name) values('Yemen');
INSERT INTO country(name) values('Zambia');
INSERT INTO country(name) values('Zimbabwe');

COMMIT;
